[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd apps/backend && python manage.py migrate && gunicorn culturalite_backend.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app/apps/backend"
DJANGO_SETTINGS_MODULE = "culturalite_backend.settings"
