services:
  # Frontend Service
  - type: web
    name: culturalite-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build:frontend
    startCommand: npm run start --workspace=frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NEXT_PUBLIC_API_URL
        value: https://culturalite-backend.onrender.com
    domains:
      - culturalite-frontend.onrender.com

  # Backend Service  
  - type: web
    name: culturalite-backend
    env: python
    plan: free
    buildCommand: cd apps/backend && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: cd apps/backend && gunicorn culturalite_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: culturalite_backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: culturalite-backend.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://culturalite-frontend.onrender.com,http://localhost:3000
      - key: DATABASE_URL
        fromDatabase:
          name: culturalite-db
          property: connectionString
    domains:
      - culturalite-backend.onrender.com

databases:
  - name: culturalite-db
    databaseName: culturalite
    user: culturalite_user
    plan: free
