# Generated by Django 5.2.3 on 2025-06-26 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the category (e.g., 'Music', 'Dance', 'Festival')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the event', max_length=200)),
                ('description', models.TextField(help_text='A detailed description of the event')),
                ('city', models.CharField(help_text='The city where the event will take place', max_length=100)),
                ('event_date', models.DateTimeField(help_text='The date and time of the event')),
                ('image_url', models.URLField(help_text="The URL of the event's image, hosted on Cloudinary", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='The moderation status of the event', max_length=10)),
                ('category', models.ForeignKey(help_text='The category this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.category')),
                ('vendor', models.ForeignKey(help_text='The vendor (user) who submitted this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
    ]
