# Generated by Django 5.2.3 on 2025-06-26 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, help_text='Name of the organization or business', max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('website', models.URLField(blank=True, help_text='Organization website URL')),
                ('bio', models.TextField(blank=True, help_text='Brief description about the organizer or organization', max_length=1000)),
                ('avatar', models.URLField(blank=True, help_text='Profile picture URL (stored in Cloudinary)')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the organizer has been verified by platform admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
